name: 'Changelog Filer'
description: 'Reading a changelog comment, writing it to a file. And as an extra, determines change type.'
author: 'Simon Blomsterlund'

inputs:
  prcomment:
    required: true
    description: 'the actual comment'
  
  write: 
    required: false
    description: 'Write to the changelog'
    default: true

  filename:
    required: false
    description: 'Name of the changelog file'
    default: 'CHANGELOG.md'
  
  filelocation:
    required: false
    description: 'File location relative to root, leave empty for root'
    default: ''
  
outputs:
  version_type:
    description: 'Version type as one of [MAJOR, MINOR, PATCH]'
  
  json_changelog:
    description: 'Changelog as json'
  
  md_changelog:
    description: 'Changelog as md formatted string.'


runs:
  using: 'node16'
  main: 'lib/index.js'